language: cpp
script: mkdir build ; cd build ; CXXFLAGS="-std=c++11 -stdlib=libc++ -g -Wall" cmake ../ ; make ; ./test-runner --on-failure ./dump-backtrace
compiler:
    - clang
before_script:
    - cd test
